default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'ali') %>
  host: <%= ENV.fetch('DB_HOST', 'db') %> # Use 'db' if using Docker Compose
  port: <%= ENV.fetch('DB_PORT', 5432) %>

development:
  <<: *default
  database: deployment

test:
  <<: *default
  database: test_deployment

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME', 'deployment_production') %>
