default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 'ali'
  host: localhost

development:
  <<: *default
  database: deployment

test:
  <<: *default
  database: test_deployment

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV['DATABASE_URL'] %>